openapi: 3.1.0
info:
  title: API D2C Brand Store
  description: API D2C Brand Store
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
security:
  - bearerAuth: []
paths:
  /auth/register:
    $ref: './paths/authApi.yaml#/~1auth~1register'
  /auth/login:
    $ref: './paths/authApi.yaml#/~1auth~1login'
  /user/profile:
    $ref: './paths/userApi.yaml#/~1user~1profile'
  /user/update:
    $ref: './paths/userApi.yaml#/~1user~1update'
  /user/delete:
    $ref: './paths/userApi.yaml#/~1user~1delete'
  /user/change-password:
    $ref: './paths/userApi.yaml#/~1user~1change-password'
  /products/add:
    $ref: './paths/productApi.yaml#/~1products~1add'
  /products:
    $ref: './paths/productApi.yaml#/~1products'
  /products/category/{categoryId}:
    $ref: './paths/productApi.yaml#/~1products~1category~1{categoryId}'
  /products/{productId}:
    $ref: './paths/productApi.yaml#/~1products~1{productId}'
  /products/update/{productId}:
    $ref: './paths/productApi.yaml#/~1products~1update~1{productId}'
  /products/delete/{productId}:
    $ref: './paths/productApi.yaml#/~1products~1delete~1{productId}'
  /address:
    $ref: './paths/addressApi.yaml#/~1address'
  /address/{addressId}:
    $ref: './paths/addressApi.yaml#/~1address~1{addressId}'
  /address/add:
    $ref: './paths/addressApi.yaml#/~1address~1add'
  /address/update/{addressId}:
    $ref: './paths/addressApi.yaml#/~1address~1update~1{addressId}'
  /address/delete/{addressId}:
    $ref: './paths/addressApi.yaml#/~1address~1delete~1{addressId}'
  /wishlists:
    $ref: './paths/wishlistApi.yaml#/~1wishlists'
  /wishlists/add:
    $ref: './paths/wishlistApi.yaml#/~1wishlists~1add'
  /wishlists/delete/{wishlistId}:
    $ref: './paths/wishlistApi.yaml#/~1wishlists~1delete~1{wishlistId}'
  /categories:
    $ref: './paths/categoryApi.yaml#/~1categories'
  /categories/add:
    $ref: './paths/categoryApi.yaml#/~1categories~1add'
  /categories/update/{categoryId}:
    $ref: './paths/categoryApi.yaml#/~1categories~1update~1{categoryId}'
  /categories/delete/{categoryId}:
    $ref: './paths/categoryApi.yaml#/~1categories~1delete~1{categoryId}'
  /bank-accounts:
    $ref: './paths/bankAccountApi.yaml#/~1bank-accounts'
  /bank-accounts/{bankAccountId}:
    $ref: './paths/bankAccountApi.yaml#/~1bank-accounts~1{bankAccountId}'
  /bank-accounts/add:
    $ref: './paths/bankAccountApi.yaml#/~1bank-accounts~1add'
  /bank-accounts/update/{bankAccountId}:
    $ref: './paths/bankAccountApi.yaml#/~1bank-accounts~1update~1{bankAccountId}'
  /bank-accounts/delete/{bankAccountId}:
    $ref: './paths/bankAccountApi.yaml#/~1bank-accounts~1delete~1{bankAccountId}'
  /carts:
    $ref: './paths/cartApi.yaml#/~1carts'
  /carts/add:
    $ref: './paths/cartApi.yaml#/~1carts~1add'
  /carts/quantity:
    $ref: './paths/cartApi.yaml#/~1carts~1quantity~1{cartItemId}'
  /carts/delete/{cartItemId}:
    $ref: './paths/cartApi.yaml#/~1carts~1delete~1{cartItemId}'
  /carts/delete:
    $ref: './paths/cartApi.yaml#/~1carts~1delete'
  /orders/create:
    $ref: './paths/orderApi.yaml#/~1orders~1create'
  /orders:
    $ref: './paths/orderApi.yaml#/~1orders'
  /orders/me:
    $ref: './paths/orderApi.yaml#/~1orders~1me'
  /orders/{orderId}:
    $ref: './paths/orderApi.yaml#/~1orders~1{orderId}'
  /orders/status/{orderId}:
    $ref: './paths/orderApi.yaml#/~1orders~1status~1{orderId}'
  /orders/cancel/{orderId}:
    $ref: './paths/orderApi.yaml#/~1orders~1cancel~1{orderId}'
  /payment:
    $ref: './paths/paymentApi.yaml#/~1payment'
  /payment/{orderId}:
    $ref: './paths/paymentApi.yaml#/~1payment~1{orderId}'
  /payment/create:
    $ref: './paths/paymentApi.yaml#/~1payment~1create'
  /payment/{orderId}/status:
    $ref: './paths/paymentApi.yaml#/~1payment~1{orderId}~1status'
  /payment/midtrans/callback:
    $ref: './paths/paymentApi.yaml#/~1payment~1midtrans~1callback'
  /payment/delete/{orderId}:
    $ref: './paths/paymentApi.yaml#/~1payment~1delete~1{orderId}'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  examples:
    $ref: './components/examples.yaml'